export const s = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#0e0e0e",
    fontFamily: "sans-serif",
    color: "#e8e8e8",
    boxSizing: "border-box",
  },
  container: {
    maxWidth: "600px",
    margin: "0 auto",
    width: "100%",
    padding: "60px 40px 40px 40px",
    boxSizing: "border-box",
  },
  header: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    gap: "16px",
    marginBottom: "40px",
  },
  title: {
    fontSize: "80px",
    fontWeight: "900",
    color: "#e8e8e8",
    letterSpacing: "4px",
    lineHeight: "80px",
    margin: 0,
  },
  badge: {
    backgroundColor: "#c8f060",
    padding: "3px 10px",
    marginBottom: "10px",
    display: "inline-block",
  },
  badgeText: {
    color: "#0e0e0e",
    fontSize: "11px",
    fontWeight: "700",
    letterSpacing: "1px",
  },
  inputRow: { display: "flex", flexDirection: "row", marginBottom: "24px" },
  input: {
    flex: 1,
    backgroundColor: "#161616",
    border: "1px solid #2a2a2a",
    borderRight: "none",
    color: "#e8e8e8",
    fontSize: "14px",
    padding: "14px",
    outline: "none",
  },
  addBtn: {
    backgroundColor: "#c8f060",
    padding: "0 22px",
    border: "none",
    color: "#0e0e0e",
    fontWeight: "900",
    fontSize: "14px",
    letterSpacing: "2px",
    cursor: "pointer",
  },
  filters: {
    display: "flex",
    flexDirection: "row",
    gap: "4px",
    marginBottom: "20px",
  },
  filterBtn: {
    backgroundColor: "transparent",
    border: "1px solid #2a2a2a",
    padding: "6px 14px",
    color: "#555",
    fontSize: "10px",
    letterSpacing: "1.5px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  filterActive: {
    backgroundColor: "#e8e8e8",
    borderColor: "#e8e8e8",
    color: "#0e0e0e",
  },
  taskList: { display: "flex", flexDirection: "column" },
  taskItem: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "14px",
    backgroundColor: "#161616",
    border: "1px solid #2a2a2a",
    padding: "16px",
    marginBottom: "2px",
  },
  taskDone: { opacity: 0.45 },
  checkBtn: {
    width: "20px",
    height: "20px",
    backgroundColor: "transparent",
    border: "1.5px solid #2a2a2a",
    color: "#e8e8e8",
    fontSize: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: 0,
  },
  taskText: {
    flex: 1,
    fontSize: "13px",
    color: "#e8e8e8",
    textAlign: "left",
    cursor: "text",
  },
  taskTextDone: { textDecoration: "line-through", color: "#555" },
  iconBtn: {
    background: "none",
    border: "none",
    color: "#555",
    fontSize: "16px",
    cursor: "pointer",
    padding: "0 4px",
  },
  editInput: {
    flex: 1,
    backgroundColor: "#0e0e0e",
    border: "1px solid #c8f060",
    color: "#e8e8e8",
    fontSize: "13px",
    padding: "6px 10px",
    outline: "none",
  },
  saveBtn: {
    backgroundColor: "#c8f060",
    border: "none",
    color: "#0e0e0e",
    fontSize: "10px",
    fontWeight: "bold",
    letterSpacing: "1px",
    padding: "6px 12px",
    cursor: "pointer",
  },
  cancelBtn: {
    background: "none",
    border: "none",
    color: "#555",
    fontSize: "14px",
    cursor: "pointer",
    padding: "0 4px",
  },
  empty: {
    textAlign: "center",
    color: "#555",
    fontSize: "12px",
    letterSpacing: "2px",
    padding: "60px 0",
  },
  footer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "24px",
  },
  muted: { color: "#555", fontSize: "10px", letterSpacing: "1px" },
  clearBtn: {
    background: "none",
    border: "none",
    color: "#555",
    fontSize: "10px",
    letterSpacing: "1px",
    cursor: "pointer",
    padding: 0,
  },
};
